/**
 * Makes the bundled `conductor` CLI available to agents at
 * `~/.stagehand/bin/conductor`.
 *
 * In development, the conductor package lives at `native/conductor/` (prepared
 * by `scripts/prepare-conductor.ts`). In production, electron-builder copies it
 * to `process.resourcesPath/conductor/` via extraResources.
 *
 * The installed binary is a small Node.js script (not a shell one-liner) that:
 *
 *   1. Detects `--device web` / `--device web:*` in argv.
 *   2. Reads `CONDUCTOR_WEB_DEVICE_ID` from env (set by `startAgent` when
 *      spawning the Claude CLI process).
 *   3. Rewrites argv (`--device web` → `--device {CONDUCTOR_WEB_DEVICE_ID}`)
 *      so the agent's conductor commands target the pre-acquired browser.
 *   4. Execs the real conductor CLI with the rewritten argv.
 *
 * This runs before Claude's Bash tool sees anything, so it works regardless of
 * permission mode (including `bypassPermissions`, where `can_use_tool`
 * control_requests are skipped for auto-approved tools).
 */

import { app } from "electron";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { info, warn } from "../../../app/lib/logger";

const BIN_DIR = path.join(os.homedir(), ".stagehand", "bin");
const BIN_PATH = path.join(BIN_DIR, "conductor");

/**
 * Resolve the directory containing the conductor package.
 *
 * - Packaged app: `process.resourcesPath/conductor/`
 * - Development: `<cwd>/native/conductor/`
 */
function getConductorDir(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, "conductor")
    : path.join(process.cwd(), "native", "conductor");
}

/**
 * Build the shim script body. Kept as a separate function so the inline
 * template literal is easy to read and we can run it through the type
 * checker as a normal string.
 *
 * The shim rewrites `--device web` (or `--device web:chromium`) to the
 * specific device ID from `CONDUCTOR_WEB_DEVICE_ID` (set by Stagehand when
 * spawning the agent process). No HTTP calls needed — the env var is all
 * the shim needs.
 */
function buildShimScript(entryPoint: string): string {
  return `#!/usr/bin/env node
/* eslint-disable */
// Auto-generated by Stagehand's conductorInstaller. Do not edit manually.
'use strict';

const { spawnSync } = require('child_process');

const CONDUCTOR_ENTRY = ${JSON.stringify(entryPoint)};

function rewriteDeviceArg(argv, qualifiedDeviceId) {
  const out = argv.slice();
  for (let i = 0; i < out.length - 1; i++) {
    if (out[i] === '--device') {
      const val = out[i + 1];
      if (val === 'web' || val === 'web:chromium') {
        out[i + 1] = qualifiedDeviceId;
        return out;
      }
    }
  }
  return out;
}

function hasWebDeviceArg(argv) {
  for (let i = 0; i < argv.length - 1; i++) {
    if (argv[i] === '--device') {
      const v = argv[i + 1];
      if (v === 'web' || v === 'web:chromium' || v.startsWith('web:chromium:')) {
        return true;
      }
    }
  }
  return false;
}

const forwardedArgs = process.argv.slice(2);
let finalArgs = forwardedArgs;

if (hasWebDeviceArg(forwardedArgs) && process.env.CONDUCTOR_WEB_DEVICE_ID) {
  finalArgs = rewriteDeviceArg(forwardedArgs, process.env.CONDUCTOR_WEB_DEVICE_ID);
}

const result = spawnSync(
  process.execPath,
  [CONDUCTOR_ENTRY].concat(finalArgs),
  { stdio: 'inherit', env: process.env }
);
process.exit(result.status == null ? 1 : result.status);
`;
}

/**
 * Write the shim to `~/.stagehand/bin/conductor`. Overwrites any existing
 * script to ensure it always points to the current app installation.
 */
export function installConductor(): void {
  const conductorDir = getConductorDir();
  const entryPoint = path.join(
    conductorDir,
    "node_modules",
    "@houwert",
    "conductor",
    "dist",
    "index.js",
  );

  if (!fs.existsSync(entryPoint)) {
    warn(
      `[conductor-installer] Entry point not found at ${entryPoint}, skipping`,
    );

    return;
  }

  const script = buildShimScript(entryPoint);

  try {
    fs.mkdirSync(BIN_DIR, { recursive: true });
    fs.writeFileSync(BIN_PATH, script);
    fs.chmodSync(BIN_PATH, 0o755);
    info(`[conductor-installer] Installed conductor CLI to ${BIN_PATH}`);
  } catch (e) {
    warn(`[conductor-installer] Failed to install conductor: ${String(e)}`);
  }
}

/**
 * Return the absolute path to the conductor SKILL.md file, or `null` if the
 * bundled conductor package is not available.
 */
export function getConductorSkillPath(): string | null {
  const conductorDir = getConductorDir();
  const skillPath = path.join(
    conductorDir,
    "node_modules",
    "@houwert",
    "conductor",
    "skills",
    "conductor",
    "SKILL.md",
  );

  return fs.existsSync(skillPath) ? skillPath : null;
}
