/**
 * Makes the bundled `conductor` CLI available to agents at
 * `~/.argus/bin/conductor`.
 *
 * In development, the conductor package lives at `native/conductor/` (prepared
 * by `scripts/prepare-conductor.ts`). In production, electron-builder copies it
 * to `process.resourcesPath/conductor/` via extraResources.
 *
 * The installed binary is a small Node.js script that lazily resolves
 * `--device ios` / `--device web` into a real device ID the first time the
 * agent runs a conductor command:
 *
 *   1. Detects `--device ios` / `--device web` (or `web:chromium`) in argv.
 *   2. POSTs to the Argus MCP server's `/argus/acquire-device`
 *      endpoint (URL in `ARGUS_RESOLVER_URL`, agent ID in
 *      `ARGUS_AGENT_ID`). Argus acquires the simulator / headless
 *      Chromium on demand and returns its ID.
 *   3. Rewrites argv with the real device ID and execs the real conductor
 *      CLI.
 *
 * Lazy acquisition means agents that never touch a runtime never spin one up.
 * This runs before Claude's Bash tool sees anything, so it works regardless of
 * permission mode (including `bypassPermissions`, where `can_use_tool`
 * control_requests are skipped for auto-approved tools).
 */

import { app } from "electron";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { info, warn } from "../../../app/lib/logger";

const BIN_DIR = path.join(os.homedir(), ".argus", "bin");
const BIN_PATH = path.join(BIN_DIR, "conductor");

/**
 * Resolve the directory containing the conductor package.
 *
 * - Packaged app: `process.resourcesPath/conductor/`
 * - Development: `<cwd>/native/conductor/`
 */
function getConductorDir(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, "conductor")
    : path.join(process.cwd(), "native", "conductor");
}

/**
 * Build the shim script body. Kept as a separate function so the inline
 * template literal is easy to read and we can run it through the type
 * checker as a normal string.
 *
 * The shim inspects argv for `--device ios` / `--device web` and, when one is
 * found, POSTs to the Argus resolver to lazily acquire the corresponding
 * runtime and get back a real device ID. Argv is then rewritten with the
 * resolved ID before the real conductor is invoked.
 */
function buildShimScript(entryPoint: string): string {
  return `#!/usr/bin/env node
/* eslint-disable */
// Auto-generated by Argus's conductorInstaller. Do not edit manually.
'use strict';

const { spawn } = require('child_process');
const http = require('http');

const CONDUCTOR_ENTRY = ${JSON.stringify(entryPoint)};

function findDeviceFlag(argv) {
  for (let i = 0; i < argv.length - 1; i++) {
    if (argv[i] === '--device') {
      return { index: i + 1, value: argv[i + 1] };
    }
  }
  return null;
}

function classifyDevice(value) {
  if (!value) return null;
  if (value === 'web' || value === 'web:chromium') return 'web';
  if (value === 'ios') return 'ios';
  return null; // Already a concrete device ID — pass through.
}

function resolveDevice(platform) {
  const url = process.env.ARGUS_RESOLVER_URL;
  const agentId = process.env.ARGUS_AGENT_ID;
  if (!url || !agentId) {
    throw new Error(
      'Argus resolver not configured (ARGUS_RESOLVER_URL / ARGUS_AGENT_ID missing)'
    );
  }
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const body = JSON.stringify({ agent_id: agentId, platform });
    const req = http.request(
      {
        method: 'POST',
        hostname: parsed.hostname,
        port: parsed.port,
        path: parsed.pathname,
        headers: {
          'content-type': 'application/json',
          'content-length': Buffer.byteLength(body),
        },
      },
      (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => {
          const text = Buffer.concat(chunks).toString('utf-8');
          if (res.statusCode !== 200) {
            return reject(new Error('Resolver ' + res.statusCode + ': ' + text));
          }
          try {
            const parsedBody = JSON.parse(text);
            if (!parsedBody.device_id) {
              return reject(new Error('Resolver returned no device_id'));
            }
            resolve(parsedBody.device_id);
          } catch (e) {
            reject(e);
          }
        });
      }
    );
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

(async () => {
  const forwardedArgs = process.argv.slice(2);
  const flag = findDeviceFlag(forwardedArgs);
  const platform = flag ? classifyDevice(flag.value) : null;

  let finalArgs = forwardedArgs;
  if (flag && platform) {
    try {
      const deviceId = await resolveDevice(platform);
      finalArgs = forwardedArgs.slice();
      finalArgs[flag.index] = deviceId;
    } catch (e) {
      process.stderr.write(
        'argus: failed to resolve --device ' + platform + ': ' + e.message + '\\n'
      );
      process.exit(1);
    }
  }

  const child = spawn(
    process.execPath,
    [CONDUCTOR_ENTRY].concat(finalArgs),
    { stdio: 'inherit', env: process.env }
  );
  child.on('exit', (code, signal) => {
    if (signal) {
      process.kill(process.pid, signal);
      return;
    }
    process.exit(code == null ? 1 : code);
  });
  child.on('error', (e) => {
    process.stderr.write('argus: failed to spawn conductor: ' + e.message + '\\n');
    process.exit(1);
  });
})();
`;
}

/**
 * Write the shim to `~/.argus/bin/conductor`. Overwrites any existing
 * script to ensure it always points to the current app installation.
 */
export function installConductor(): void {
  const conductorDir = getConductorDir();
  const entryPoint = path.join(
    conductorDir,
    "node_modules",
    "@houwert",
    "conductor",
    "dist",
    "index.js",
  );

  if (!fs.existsSync(entryPoint)) {
    warn(
      `[conductor-installer] Entry point not found at ${entryPoint}, skipping`,
    );

    return;
  }

  const script = buildShimScript(entryPoint);

  try {
    fs.mkdirSync(BIN_DIR, { recursive: true });
    fs.writeFileSync(BIN_PATH, script);
    fs.chmodSync(BIN_PATH, 0o755);
    info(`[conductor-installer] Installed conductor CLI to ${BIN_PATH}`);
  } catch (e) {
    warn(`[conductor-installer] Failed to install conductor: ${String(e)}`);
  }
}

/**
 * Return the absolute path to the conductor SKILL.md file, or `null` if the
 * bundled conductor package is not available.
 */
export function getConductorSkillPath(): string | null {
  const conductorDir = getConductorDir();
  const skillPath = path.join(
    conductorDir,
    "node_modules",
    "@houwert",
    "conductor",
    "skills",
    "conductor",
    "SKILL.md",
  );

  return fs.existsSync(skillPath) ? skillPath : null;
}
